// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuynYPHGV1h_FppHGZztLSq3uhX2EAl2Y',
    appId: '1:1050701892775:web:2dd249c33730e4b4291f82',
    messagingSenderId: '1050701892775',
    projectId: 'saloonshop-5b880',
    authDomain: 'saloonshop-5b880.firebaseapp.com',
    storageBucket: 'saloonshop-5b880.appspot.com',
    measurementId: 'G-RS6HTVP5LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZk1ZwivwaYXycAkPlHTVc7KHIgeXH7jk',
    appId: '1:1050701892775:android:828f8eae8769c904291f82',
    messagingSenderId: '1050701892775',
    projectId: 'saloonshop-5b880',
    storageBucket: 'saloonshop-5b880.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA30tEi7_WGzSoK1mQap7qmSjFjQBxpqM',
    appId: '1:1050701892775:ios:459488ab7a9a6a30291f82',
    messagingSenderId: '1050701892775',
    projectId: 'saloonshop-5b880',
    storageBucket: 'saloonshop-5b880.appspot.com',
    androidClientId: '1050701892775-am4m05lgf5217g0n9v1q7u3gnav41b3j.apps.googleusercontent.com',
    iosClientId: '1050701892775-ka8ud670sq5ose35fpmcklcpq2kr6mmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.saloonCultAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA30tEi7_WGzSoK1mQap7qmSjFjQBxpqM',
    appId: '1:1050701892775:ios:459488ab7a9a6a30291f82',
    messagingSenderId: '1050701892775',
    projectId: 'saloonshop-5b880',
    storageBucket: 'saloonshop-5b880.appspot.com',
    androidClientId: '1050701892775-am4m05lgf5217g0n9v1q7u3gnav41b3j.apps.googleusercontent.com',
    iosClientId: '1050701892775-ka8ud670sq5ose35fpmcklcpq2kr6mmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.saloonCultAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuynYPHGV1h_FppHGZztLSq3uhX2EAl2Y',
    appId: '1:1050701892775:web:38222d207c874c0b291f82',
    messagingSenderId: '1050701892775',
    projectId: 'saloonshop-5b880',
    authDomain: 'saloonshop-5b880.firebaseapp.com',
    storageBucket: 'saloonshop-5b880.appspot.com',
    measurementId: 'G-LYWYEFYJ4R',
  );
}
